on:
  push:
    branches:
      - master
jobs:
  main:
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run git config
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Run standard-version
        run: |
          npm install semver yaml
          npx standard-version
          git push --follow-tags origin master
      - uses: tnc1997/github-actions/actions/setup-flutter@setup-flutter_v1
        with:
          channel: 'dev'
      - name: Run gpg decrypt
        env:
          ARCHIVE_PASSPHRASE: ${{ secrets.ARCHIVE_PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase "$ARCHIVE_PASSPHRASE" --output "archive.tar" archive.tar.gpg
          tar -xf archive.tar
          rm archive.tar
      - name: Run flutter build appbundle
        run: flutter build appbundle
      - uses: actions/upload-artifact@v1
        with:
         name: android
         path: ./build/app/outputs/bundle/release/app-release.aab
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ./api-6938910936944731223-873461-5d98d1eb9a1e.json
          packageName: app.thomasclark.tflapiexplorer
          releaseFile: ./build/app/outputs/bundle/release/app-release.aab
          track: internal
