on:
  push:
    branches:
      - master
jobs:
  main:
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: tnc1997/github-actions/setup-flutter@master
        with:
          channel: 'dev'
      - name: Run gpg decrypt
        env:
          ARCHIVE_PASSPHRASE: ${{ secrets.ARCHIVE_PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase "$ARCHIVE_PASSPHRASE" --output "archive.tar" archive.tar.gpg
          tar -xf archive.tar
          rm archive.tar
      - name: Run flutter build appbundle
        run: flutter build appbundle
      - uses: actions/setup-ruby@master
        with:
          ruby-version: '2.x'
      - name: Run fastlane deploy
        run: |
          cd android
          bundle install
          bundle exec fastlane deploy
