name: Test workflow
on: [push]
jobs:
  run:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: tnc1997/github-actions/setup-flutter@master
        with:
          channel: 'stable'
      - run: flutter test
